-- MySQL Script generated by MySQL Workbench
-- Sat Oct 19 17:44:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema raketedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema raketedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `raketedb` DEFAULT CHARACTER SET utf8 ;
USE `raketedb` ;

-- -----------------------------------------------------
-- Table `raketedb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`role` (
  `idrole` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`country` (
  `idcountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`user` (
  `iduser` INT NOT NULL,
  `country_idcountry` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` LONGTEXT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_country1_idx` (`country_idcountry` ASC),
  CONSTRAINT `fk_user_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `raketedb`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`estate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`estate` (
  `idestate` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country_idcountry` INT NOT NULL,
  PRIMARY KEY (`idestate`),
  INDEX `fk_estate_country1_idx` (`country_idcountry` ASC),
  CONSTRAINT `fk_estate_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `raketedb`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`city` (
  `idcity` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `latitude` FLOAT NULL,
  `estate_idestate` INT NOT NULL,
  PRIMARY KEY (`idcity`),
  INDEX `fk_city_estate1_idx` (`estate_idestate` ASC),
  CONSTRAINT `fk_city_estate1`
    FOREIGN KEY (`estate_idestate`)
    REFERENCES `raketedb`.`estate` (`idestate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`user_has_role` (
  `iduser_has_role` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`iduser_has_role`),
  INDEX `fk_user_has_role_user_idx` (`user_iduser` ASC),
  INDEX `fk_user_has_role_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `raketedb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `raketedb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`shelter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`shelter` (
  `idshelter` INT NOT NULL,
  `city_idcity` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`idshelter`),
  INDEX `fk_shelter_city1_idx` (`city_idcity` ASC),
  CONSTRAINT `fk_shelter_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `raketedb`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`safepoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`safepoint` (
  `idsafepoint` INT NOT NULL,
  `city_idcity` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`idsafepoint`),
  INDEX `fk_safepoint_city1_idx` (`city_idcity` ASC),
  CONSTRAINT `fk_safepoint_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `raketedb`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raketedb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raketedb`.`report` (
  `idreport` INT NOT NULL,
  `city_idcity` INT NOT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `description` VARCHAR(250) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idreport`),
  INDEX `fk_report_city1_idx` (`city_idcity` ASC),
  CONSTRAINT `fk_report_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `raketedb`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
